export const cartActionTypes = {
  TOGGLE_CART_DROPDOWN: "TOGGLE_CART_DROPDOWN",
  ADD_CART_ITEM: "ADD_CART_ITEM",
  DECREASE_CART_ITEM: "DECREASE_CART_ITEM",
  REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
};

export default cartActionTypes;
